// <auto-generated />
using Oip.Dal.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Oip.Dal.Sqlite.Migrations
{
    [DbContext(typeof(OipContext))]
    partial class OipContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("olp")
                .HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Oip.Models.Uom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseUomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtendetProperty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Formula")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalizedName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_Uom_Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Uom_Name");

                    b.ToTable("Uoms", "olp");
                });
#pragma warning restore 612, 618
        }
    }
}
